const state={capabilities:null,mode:'basic',viewerMode:'basic',history:[],historyIndex:-1,lastResults:null,currentClass:null};
const form=document.querySelector('#search-form'),filters=document.querySelector('#filters'),template=document.querySelector('#filter-template'),statusNode=document.querySelector('#status'),resultsNode=document.querySelector('#results'),emptyNode=document.querySelector('#empty-state'),searchButton=document.querySelector('#search-button'),a3qlError=document.querySelector('#a3ql-error'),viewer=document.querySelector('#class-viewer');
function switchMode(mode){state.mode=mode;const basic=mode==='basic';document.querySelector('#basic-panel').hidden=!basic;document.querySelector('#advanced-panel').hidden=basic;document.querySelector('#basic-tab').classList.toggle('active',basic);document.querySelector('#advanced-tab').classList.toggle('active',!basic);a3qlError.hidden=true;}
function addFilter(initial={field:'displayName',operator:'eq',value:''}){const fragment=template.content.cloneNode(true),row=fragment.querySelector('.filter-row');row.querySelector('.filter-field').value=initial.field;row.querySelector('.filter-operator').value=initial.operator;row.querySelector('.filter-value').value=initial.value;row.querySelector('.remove-filter').addEventListener('click',()=>row.remove());filters.appendChild(fragment);}
function coerceValue(field,raw){if(field==='scope'&&raw.trim()!==''){const value=Number(raw);if(Number.isNaN(value))throw new Error('Scope must be numeric.');return value;}return raw;}
function payload(){return{root:document.querySelector('#root').value||null,filters:[...filters.querySelectorAll('.filter-row')].map(row=>{const field=row.querySelector('.filter-field').value,raw=row.querySelector('.filter-value').value.trim();return{field,operator:row.querySelector('.filter-operator').value,value:coerceValue(field,raw)};}).filter(item=>item.value!==''),limit:Number(document.querySelector('#limit').value)};}
function renderResults(data,elapsed){state.lastResults=data;document.querySelector('#export-results').disabled=!(data.results||[]).length;resultsNode.replaceChildren();const items=data.results||[];for(const item of items){const row=document.createElement('tr');row.tabIndex=0;for(const value of[item.displayName||'—',item.classname,item.root,item.parent||'—']){const cell=document.createElement('td');cell.textContent=value;row.appendChild(cell);}const open=()=>openClass(item.root,item.classname,{push:true});row.addEventListener('click',open);row.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}});resultsNode.appendChild(row);}emptyNode.hidden=items.length>0;emptyNode.textContent=items.length?'':'No results.';statusNode.textContent=`${items.length} result${items.length===1?'':'s'} · ${elapsed.toFixed(0)} ms`;}
async function request(url,body){const started=performance.now(),response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok||data.status!=='ok')throw new Error(data?.error?.message||`Request failed (${response.status}).`);renderResults(data.data,performance.now()-started);}
function cppValue(value){if(typeof value==='string')return JSON.stringify(value);if(Array.isArray(value))return `{${value.map(cppValue).join(', ')}}`;if(value&&typeof value==='object')return JSON.stringify(value);return String(value).toLowerCase();}
function cppClass(data){const parent=data.parent?` : ${data.parent}`:'';return `class ${data.classname}${parent}\n{\n${Object.entries(data.localProperties).map(([k,v])=>`    ${k} = ${cppValue(v)};`).join('\n')}\n};`;}
function safeName(value){return String(value||'export').replace(/[^A-Za-z0-9._-]+/g,'_').replace(/^_+|_+$/g,'')||'export';}
function csvCell(value){const text=String(value??'');return /[",\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text;}
function sqfString(value){return `"${String(value??'').replaceAll('"','""')}"`;}
function downloadText(filename,mime,text){const blob=new Blob([text],{type:`${mime};charset=utf-8`}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);}
function resultExport(format,data){const items=data.results||[];if(Number.isInteger(data.total)&&data.total!==items.length)throw new Error(`Export refused: current page contains ${items.length} of ${data.total} results.`);if(format==='json')return{ext:'json',mime:'application/json',text:JSON.stringify({snapshot:data.snapshot,results:items},null,2)};if(format==='csv'){const rows=[['displayName','classname','root','parent'],...items.map(item=>[item.displayName,item.classname,item.root,item.parent])];return{ext:'csv',mime:'text/csv',text:rows.map(row=>row.map(csvCell).join(',')).join('\n')};}if(format==='markdown'){const lines=['| Display name | Classname | Root | Parent |','|---|---|---|---|',...items.map(item=>`| ${item.displayName||''} | ${item.classname} | ${item.root} | ${item.parent||''} |`)];return{ext:'md',mime:'text/markdown',text:lines.join('\n')};}return{ext:'sqf',mime:'text/plain',text:`[${items.map(item=>sqfString(item.classname)).join(',')}];`};}
function classExport(format,data){if(format==='json')return{ext:'json',mime:'application/json',text:JSON.stringify(data,null,2)};if(format==='markdown'){const props=Object.entries(data.resolvedProperties).map(([k,v])=>`| ${k} | ${Array.isArray(v)?v.join(', '):String(v)} |`);return{ext:'md',mime:'text/markdown',text:[`# ${data.classname}`,'',`- Root: ${data.root}`,`- Parent: ${data.parent||'None'}`,'','| Property | Value |','|---|---|',...props].join('\n')};}if(format==='cpp')return{ext:'hpp',mime:'text/plain',text:cppClass(data)};return{ext:'sqf',mime:'text/plain',text:`[${sqfString(data.root)},${sqfString(data.classname)},${sqfString(data.parent||'')}];`};}
function setViewerMode(mode){state.viewerMode=mode;const basic=mode==='basic';document.querySelector('#viewer-basic').hidden=!basic;document.querySelector('#viewer-advanced').hidden=basic;document.querySelector('#viewer-basic-tab').classList.toggle('active',basic);document.querySelector('#viewer-advanced-tab').classList.toggle('active',!basic);}
function updateHistoryButtons(){document.querySelector('#viewer-back').disabled=state.historyIndex<=0;document.querySelector('#viewer-forward').disabled=state.historyIndex<0||state.historyIndex>=state.history.length-1;}
function syncUrl(root,classname,replace=false){const url=new URL(location.href);url.searchParams.set('root',root);url.searchParams.set('class',classname);url.searchParams.set('view',state.viewerMode);const data={root,classname,view:state.viewerMode};if(replace)history.replaceState(data,'',url);else history.pushState(data,'',url);}
function relationButton(target,label){const button=document.createElement('button');button.type='button';button.className='relation-link';button.textContent=label||target.classname;if(!target.exists){button.disabled=true;button.title='Target is missing from this dataset.';}else button.onclick=()=>openClass(target.root,target.classname,{push:true});return button;}
function renderRelations(relations){const groups=document.querySelector('#relation-groups');groups.replaceChildren();const add=(title,targets)=>{if(!targets||!targets.length)return;const section=document.createElement('section'),heading=document.createElement('h4'),list=document.createElement('div');heading.textContent=title;list.className='relation-list';for(const target of targets)list.appendChild(relationButton(target));section.append(heading,list);groups.appendChild(section);};if(relations.parent)add('Parent',[relations.parent]);add('Children',relations.children);for(const [name,targets] of Object.entries(relations.outbound||{}))add(name[0].toUpperCase()+name.slice(1),targets);const warning=document.querySelector('#relation-warning');warning.hidden=relations.complete!==false;warning.textContent=relations.complete===false?`${(relations.missingTargets||[]).length} relation target(s) are missing from this dataset.`:'';}
async function openClass(root,classname,{push=false,replace=false}={}){const response=await fetch(`/api/class/${encodeURIComponent(root)}/${encodeURIComponent(classname)}`),body=await response.json();if(!response.ok||body.status!=='ok'){statusNode.textContent=body?.error?.message||'Unable to open class.';return;}const data=body.data,props=data.resolvedProperties;state.currentClass=data;document.querySelector('#export-class').disabled=false;document.querySelector('#viewer-root').textContent=data.root;document.querySelector('#viewer-title').textContent=props.displayName||data.classname;document.querySelector('#viewer-classname').textContent=data.classname;const basic=document.querySelector('#viewer-basic');basic.replaceChildren();const dl=document.createElement('dl');for(const key of['parent','scope','author','dlc','faction','armor','simulation']){const value=key==='parent'?data.parent:props[key];if(value===undefined||value===null)continue;const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;if(key==='parent'&&data.relations?.parent)dd.appendChild(relationButton(data.relations.parent,value));else dd.textContent=Array.isArray(value)?value.join(', '):String(value);dl.append(dt,dd);}basic.appendChild(dl);document.querySelector('#viewer-advanced').textContent=cppClass(data);renderRelations(data.relations||{children:[],outbound:{},missingTargets:[],complete:true});setViewerMode(state.viewerMode);if(push){state.history=state.history.slice(0,state.historyIndex+1);state.history.push({root,classname});state.historyIndex=state.history.length-1;syncUrl(root,classname,replace);}updateHistoryButtons();if(!viewer.open)viewer.showModal();}
async function navigateHistory(delta){const next=state.historyIndex+delta;if(next<0||next>=state.history.length)return;state.historyIndex=next;const item=state.history[next];await openClass(item.root,item.classname);syncUrl(item.root,item.classname,true);updateHistoryButtons();}
async function loadCapabilities(){const response=await fetch('/api/capabilities'),body=await response.json();if(!response.ok||body.status!=='ok')throw new Error(body?.error?.message||'Unable to load capabilities.');state.capabilities=body.data;const root=document.querySelector('#root');root.replaceChildren();for(const name of body.data.snapshot.roots){const option=document.createElement('option');option.value=name;option.textContent=name;root.appendChild(option);}document.querySelector('#dataset-summary').textContent=`${body.data.snapshot.presetLabel} · ${body.data.snapshot.gameVersion}`;const params=new URLSearchParams(location.search);if(params.get('root')&&params.get('class')){state.viewerMode=params.get('view')==='advanced'?'advanced':'basic';await openClass(params.get('root'),params.get('class'),{push:true,replace:true});}}
form.addEventListener('submit',async e=>{e.preventDefault();searchButton.disabled=true;statusNode.textContent='Searching…';try{await request('/api/basic',payload());}catch(error){resultsNode.replaceChildren();emptyNode.hidden=false;emptyNode.textContent='Search failed.';statusNode.textContent=error.message||String(error);}finally{searchButton.disabled=false;}});
document.querySelector('#run-a3ql').onclick=async()=>{const button=document.querySelector('#run-a3ql');button.disabled=true;a3qlError.hidden=true;statusNode.textContent='Executing A3QL…';try{await request('/api/advanced',{query:document.querySelector('#a3ql-source').value});}catch(error){a3qlError.textContent=error.message||String(error);a3qlError.hidden=false;}finally{button.disabled=false;}};
document.querySelector('#export-results').onclick=()=>{const error=document.querySelector('#results-export-error');error.hidden=true;try{const format=document.querySelector('#results-export-format').value,output=resultExport(format,state.lastResults||{}),snapshot=safeName(state.lastResults?.snapshot?.snapshotId||'dataset');downloadText(`a3configdb_${snapshot}_results.${output.ext}`,output.mime,output.text);}catch(exc){error.textContent=exc.message||String(exc);error.hidden=false;}};
document.querySelector('#export-class').onclick=()=>{if(!state.currentClass)return;const format=document.querySelector('#class-export-format').value,output=classExport(format,state.currentClass),name=safeName(state.currentClass.classname);downloadText(`a3configdb_${safeName(state.currentClass.root)}_${name}.${output.ext}`,output.mime,output.text);};
document.querySelector('#basic-tab').onclick=()=>switchMode('basic');document.querySelector('#advanced-tab').onclick=()=>switchMode('advanced');document.querySelector('#add-filter').onclick=()=>addFilter();document.querySelector('#reset-button').onclick=()=>{form.reset();filters.replaceChildren();addFilter();resultsNode.replaceChildren();state.lastResults=null;document.querySelector('#export-results').disabled=true;emptyNode.hidden=false;emptyNode.textContent='Run a search to display results.';statusNode.textContent='Ready.';};document.querySelector('#clear-a3ql').onclick=()=>{document.querySelector('#a3ql-source').value='';a3qlError.hidden=true;};document.querySelector('#close-viewer').onclick=()=>viewer.close();document.querySelector('#viewer-back').onclick=()=>navigateHistory(-1);document.querySelector('#viewer-forward').onclick=()=>navigateHistory(1);document.querySelector('#viewer-basic-tab').onclick=()=>{setViewerMode('basic');const item=state.history[state.historyIndex];if(item)syncUrl(item.root,item.classname,true);};document.querySelector('#viewer-advanced-tab').onclick=()=>{setViewerMode('advanced');const item=state.history[state.historyIndex];if(item)syncUrl(item.root,item.classname,true);};for(const button of document.querySelectorAll('.example-query'))button.onclick=()=>{document.querySelector('#a3ql-source').value=button.dataset.query;};window.addEventListener('popstate',event=>{const data=event.state;if(data?.root&&data?.classname){state.viewerMode=data.view==='advanced'?'advanced':'basic';openClass(data.root,data.classname);}});addFilter();switchMode('basic');updateHistoryButtons();loadCapabilities().catch(error=>{statusNode.textContent=error.message||String(error);});
